"""Offline regression checks for the shell script generated by Agent OTA."""
import ast
import base64
import hashlib
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[1]
BASH = shutil.which("bash") or r"C:\Program Files\Git\bin\bash.exe"


def shell_path(path):
    text = path.as_posix()
    return "/" + text[0].lower() + text[2:] if os.name == "nt" else text


def render_ota():
    source = (ROOT / "core/agent_daemon.sh").read_text(encoding="utf-8")
    webhook = source.split("<< 'EOF'\n", 1)[1].split("\nEOF", 1)[0]
    tree = ast.parse(webhook)
    assignments = {
        node.targets[0].id: node
        for node in ast.walk(tree)
        if isinstance(node, ast.Assign) and len(node.targets) == 1
        and isinstance(node.targets[0], ast.Name)
    }
    context = {
        "base64": base64,
        "repo_url": "https://repo.invalid/main",
        "config_mem": {"NODE_ALIAS": "test-node", "AGENT_VERSION": "5.6.29",
                       "TG_API_URL": "https://notify.invalid", "CHAT_ID": "test"},
    }

    def resolve(name):
        if name not in context:
            value = assignments[name].value
            for child in ast.walk(value):
                if isinstance(child, ast.Name) and isinstance(child.ctx, ast.Load):
                    resolve(child.id)
            context[name] = eval(compile(ast.Expression(value), "<ota>", "eval"), context)
        return context[name]

    return resolve("ota_script")


class AgentOTA(unittest.TestCase):
    def test_ota_paths(self):
        ota = render_ota()
        scenarios = (
            "version_failure", "manifest_failure", "manifest_empty",
            "installer_failure", "hash_mismatch", "syntax_failure",
            "mktemp_first", "mktemp_second", "notify_failure", "skip", "success",
        )
        for scenario in scenarios:
            with self.subTest(scenario=scenario):
                directory = Path(tempfile.mkdtemp(prefix="ips-ota-test-"))
                location = shell_path(directory)
                installer = "#!/bin/bash\nprintf installed > " + shlex.quote(location + "/installed") + "\n"
                if scenario == "syntax_failure":
                    installer = "#!/bin/bash\nif then\n"
                expected = hashlib.sha256(installer.encode()).hexdigest()
                if scenario == "hash_mismatch":
                    expected = "0" * 64
                (directory / "config.conf").write_text('AGENT_VERSION="5.6.29"\n', encoding="utf-8")
                (directory / "payload").write_text(installer, encoding="utf-8", newline="\n")
                prefix = r'''
log_notification() { printf '%s\n' "$*" >> "$TEST_DIR/notifications"; }
mktemp() {
    case "$1" in
        *manifest*) kind=manifest; fail_case=mktemp_second ;;
        *) kind=installer; fail_case=mktemp_first ;;
    esac
    [ "$SCENARIO" = "$fail_case" ] && return 1
    : > "$TEST_DIR/$kind.tmp"
    printf '%s\n' "$TEST_DIR/$kind.tmp"
}
curl() {
    local output= url= arg request="$*"
    while [ "$#" -gt 0 ]; do
        arg="$1"; shift
        case "$arg" in
            -o) output="$1"; shift ;;
            https://*) url="$arg" ;;
        esac
    done
    case "$url" in
        https://notify.invalid)
            log_notification "$request"
            [ "$SCENARIO" != notify_failure ]; return ;;
        */version.txt)
            [ "$SCENARIO" = version_failure ] && return 22
            if [ "$SCENARIO" = skip ]; then echo AGENT_VERSION=5.6.29
            else echo AGENT_VERSION=5.6.30; fi ;;
        */MANIFEST.sha256)
            case "$url" in */v5.6.30-agent/MANIFEST.sha256) ;; *) return 22 ;; esac
            case "$SCENARIO" in
                manifest_failure|notify_failure) printf partial > "$output"; return 22 ;;
                manifest_empty) : > "$output" ;;
                *) printf '%s  core/install.sh\n' "$EXPECTED" > "$output" ;;
            esac ;;
        */core/install.sh)
            if [ "$SCENARIO" = installer_failure ]; then printf partial > "$output"; return 22; fi
            cat "$TEST_DIR/payload" > "$output" ;;
        *) echo "Unexpected network request: $url" >&2; return 99 ;;
    esac
}
'''
                script = ("TEST_DIR=" + shlex.quote(location) + "\nSCENARIO=" + scenario
                          + "\nEXPECTED=" + expected + "\n" + prefix + ota)
                script = script.replace("/opt/ip_sentinel/logs/ota_upgrade.log", location + "/ota.log")
                script = script.replace("/opt/ip_sentinel/config.conf", location + "/config.conf")
                try:
                    result = subprocess.run([BASH, "-c", script], capture_output=True,
                                            text=True, timeout=15)
                    self.assertFalse((directory / "installer.tmp").exists(), result.stderr)
                    self.assertFalse((directory / "manifest.tmp").exists(), result.stderr)
                    self.assertEqual((directory / "installed").exists(), scenario == "success", result.stderr)
                    if scenario != "success":
                        self.assertTrue((directory / "notifications").exists(), result.stderr)
                        self.assertTrue((directory / "ota.log").read_text(encoding="utf-8").strip())
                    if scenario in ("success", "skip"):
                        self.assertEqual(result.returncode, 0, result.stderr)
                    else:
                        self.assertNotEqual(result.returncode, 0, result.stderr)
                    print("PASS", scenario)
                finally:
                    # Only known fixtures created by this test; no recursive cleanup.
                    (directory / "config.conf").unlink(missing_ok=True)
                    (directory / "payload").unlink(missing_ok=True)
                    (directory / "installer.tmp").unlink(missing_ok=True)
                    (directory / "manifest.tmp").unlink(missing_ok=True)
                    (directory / "installed").unlink(missing_ok=True)
                    (directory / "notifications").unlink(missing_ok=True)
                    (directory / "ota.log").unlink(missing_ok=True)
                    directory.rmdir()


if __name__ == "__main__":
    unittest.main()
